### PR TITLE
W08 02 admin page UI

### PR DESCRIPTION
**Pull request by Kyewn**
Everything working as described

Extras:
- Added reset function
- Added approve and reject filters
- Repositioned notif to bottom right

Issues:
- Dk how to apply "selected" css to selected listItem, since selecting the item is based on id and not from their index and postback has a grudge on us

Will do the same thing to reports if this is accepted

### CODE REVIEW

**Comment by Kyewn** [comment]
Remember to pull new changes ^^^

**Review by Vaneryn — CHANGES_REQUESTED** [review]
1.  Some DataContext objects are still using hardcoded connection string. **DONE**

2. Search bar needs a search button (just a button with magnifying glass icon or smtg). **DONE**

3. In .NET C#, methods should be named using PascalCase. **DONE**
image

4. This is so lame but ik it would be a pain to make a confirmation popup so I'll leave this as future enhancement task
image

5. Accepting suggestions should also prompt a confirmation since this is an irreversible action. **DONE**

6. You missed important validations here: **DONE**
image
- Need to check if this new "Slang" to "Translation" mapping is a duplicate or not,
- Need to check if the Slang or Translation actually exist in the "word" table or not, I'm getting DB error when i try to accept suggestion if the Slang or Translation doesn't exist.

These validations should also be applied for Edit Suggestion.


7. You can consider using box-shadow instead of border for inputs onfocus so we don't get the weird repositioning effect. **DONE**
image

8. You can consider using backend code to hide the nav links instead of JS so we don't see a flash of the links every time we reload the page. **DONE**

9. I think white text looks better on notifications (consistent with the theme, also contrasting color easier to see) **DONE**

10. These options are not filters, they're for sorting. Filters only show items that match the selected filter (unmatched items are not shown), sorting reorders the items while still showing all items (which is what these options are doing).
image **RENAMED LABEL "Filter" TO "Sort & Filters"**

 11. I'll look into this since I'm working on something similar for removing modal items in translation history and saved translations.
image

12. Also, can consider using the new modals I made so we dont get these derpy scrollable/uncentered/unfocused modals **DONE**

idk what else to check for now so ciao

**Comment by Vaneryn** [comment]
Oh yeah and I'll need to add modified_by and modification_date columns to 'suggestion' table since they are editable.

**Comment by Kyewn** [comment]
6. I'm thinking that system should only check if suggestion is duplicate dictionary entry, because new suggestions would have new words that doesnt exist in the db too. I also consider doing the validation when users send suggestions in the dictionary page. If users can submit their new suggestions successfully, it already means that the slang-translation mapping is not a duplicate in the `DictionaryEntries` table. Will do the validation for edit suggestions tho.

12.I need to merge your algorithm branch to use it though, it also means that ill be merging algorithm branch with this branch without needing to open a PR for algorithm branch. Do you mind? Otherwise I'll wait until you merge your algorithm branch first before I change to using your notification code.

13.Do I need to display modified_by and modification date in the approved/rejected item list while other sorts dont?

**Comment by Vaneryn** [comment]
6.
But does that address the 'word' not existing issue? If you mean the system will add new-found words for every new suggestion, then I don't think that's a good idea. We dont need to add new 'words' based on Suggestions. They are only suggestions and not finalized yet, so don't need to add useless data and waste database space by adding words that won't be used. We should only add new 'words' when a Suggestion which has new 'words' is approved. So it should go like:
- if slang-translation mapping is not duplicate
- if slang or translation word does not exist in database
- add slang or translation as new word entity
- then add DictionaryEntry

For duplicate entry, yeah that makes sense. But i think its safer if we do validations on both sides, since it's very crucial so I think it doesn't hurt to perform double validation.

12. Idk if that branch is safe to merge yet, but you could copy paste my modal code, its mostly similar to how yours already work just with different styles and structure.

13. Yeah, changing status of suggestions would count as modification too. There could be multiple admins so its useful to know who accepted/reject the suggestions and when. But btw in case you misunderstood,
image
I meant only these options in the screenshot are sorting options. Approved/Rejected are correct as filters.

**Comment by Kyewn** [comment]
6. If users input a slang/translation that doesnt have a record in the Words table, I will create a new Word record for them. But if the user suddenly chooses to change to another slang/translation, Another new record/existing record will be used instead of the record that has been created earlier. So, there will be records that are created prematurely but never used in the table, is that still ok?

**Comment by Kyewn** [comment]
Ill be reconfiguring the EntityFramework configs to add modified by and modificationdate

**Comment by Kyewn** [comment]
Can you add the fields in DB? I dk how to do it as I keep getting missing index errors for some reason..
While you're at it, you might want to set the WordValue field to unique to ensure that there wont be duplicate values.
Once you're done, please upload the seeded db, thanks.

**Comment by Vaneryn** [comment]
> Can you add the fields in DB? I dk how to do it as I keep getting missing index errors for some reason.. While you're at it, you might want to set the WordValue field to unique to ensure that there wont be duplicate values. Once you're done, please upload the seeded db, thanks.

Updated database documentation with v3.1.3 dump.

Did you mean the `dictionary_entry` table? `WordValue` in `word` table is already unique. Anyway, added unique index for `slang_id` `translation_id` pairs.

**Comment by Kyewn** [comment]
> > Can you add the fields in DB? I dk how to do it as I keep getting missing index errors for some reason.. While you're at it, you might want to set the WordValue field to unique to ensure that there wont be duplicate values. Once you're done, please upload the seeded db, thanks.
> 
> Updated database documentation with v3.1.3 dump.
> 
> Did you mean the `dictionary_entry` table? `WordValue` in `word` table is already unique. Anyway, added unique index for `slang_id` `translation_id` pairs.

im just noob. thought `WordValue` field in my Word table is not unique, but i think it should be after checking :I

**Comment by Kyewn** [comment]
Issue in commit above ^

**Comment by Vaneryn** [comment]
> Issue in commit above ^

In what case does it occur? I've tried a bunch of stuff and it seems fine to me

**Comment by Kyewn** [comment]
It happens when setting values on the new fields, in the confirm edit function (confirm button in edit modal). I didnt test getting values from them. 
image

**Comment by Vaneryn** [comment]
Im not sure, editing also works on my end. Maybe somethings wrong with your data?

Btw i just realized what you meant by this
> Do I need to display modified_by and modification date in the approved/rejected item list while other sorts don't?

My 1am brain thought u said "do we need `modified_by` and `modification_date` in approved/rejected as well". I think we should just display it at all times regardless of filter/sort since suggestions are editable.

**Comment by Kyewn** [comment]
Add transaction to discard failed multi-step process changes: https://entityframework.net/transaction
Still can't solve the error, tried cloning repo agn but it still throws the error, i think my db's problem probably.
For now, you check my commits ba, I done all the tasks.   

Edit: refreshed db and still throwing error. I dont even know now
Found this thread but cant solve also: https://entityframework.net/knowledge-base/27423059/how-do-i-clear-tracked-entities-in-entity-framework

**Comment by Vaneryn** [comment]
Im still not getting that issue, so i have no idea but maybe u can try the same thing on my laptop tomorrow. In terms of functionality, LGTM so far but I'm not sure if i covered all test cases (also 10pm brain not good).

Some minor design improvements:
1. Can add a little bit boxshadow on the notif so it doesn't blend in with background stuff **DONE**
image

2. Are u not getting this weird boxshadow on the edit modal?
image

3. Regarding this issue"
> Dk how to apply "selected" css to selected listItem, since selecting the item is based on id and not from their index and postback has a grudge on us

Im not exactly sure how you currently pass data on which list item is selected or how you generate the results. Seems like you're filling a hidden input with ID of the selected suggestion and sending it to the server? Is it not possible to then:
- while regenerating results on postback
- compare the passed ID with the ID of suggestions currently being put in the list
- if the ID is the same, set the background color of the item?
Have no idea if this works since I didn't really go through ur filtering/data retrieval/list populating logic.

If you want, I have an easier way to do this that's already implemented in `w07_01_algorithm` and `w08_03_dictionary`. For every translation or dictionary item, I made "Delete" buttons to delete specific items. What I did was:
- store the ID of the entity in a custom attribute of the button
- also hook up a server-side click handler to each button
- so when any button is clicked, I retrieve the ID value from the custom attribute to identify which specific entity I should delete
```
// Modal item container
Panel modalItem = new Panel();
modalItem.CssClass = "modal-item";

// Modal item content
LiteralControl modalItemContent = new LiteralControl($@"
    <div class='modal-item-content'>
        <h2 class='modal-item-title'>{savedTranslation.Input}</h2>
        <div class='modal-item-text'>
            <h3 class='text-title'>Translation</h3>
            <h3 class='text-content'>{savedTranslation.Output}</h3>
        </div>
        <small>Date: {savedTranslation.CreationDate}</small>
    </div>
");

// Modal item controls
Panel modalItemControls = new Panel();
modalItemControls.CssClass = "modal-item-controls";

Button btnDelete = new Button();
btnDelete.ID = (!useSession ? "btnDeleteSaved" : "btnDeleteHistory") + savedTranslation.Id;
btnDelete.ClientIDMode = ClientIDMode.Static;
btnDelete.CssClass = "modal-item-btn";
btnDelete.Text = "Delete";
btnDelete.Attributes.Add(AttrTranslationId, savedTranslation.Id.ToString()); //AttrTranslationId is just a const string
btnDelete.Click += new EventHandler(BtnDeleteTranslation_Click);
btnDelete.OnClientClick = $"confirmDelete(event, '{btnDelete.ID}');";

if (useSession)
{
    btnDelete.Attributes.Add(AttrUseSession, "true");
}

modalItemControls.Controls.Add(btnDelete);

// Add item content and item controls to item container
modalItem.Controls.Add(modalItemContent);
modalItem.Controls.Add(modalItemControls);

// Add item to modal
modal.Controls.Add(modalItem);
```
I believe it should work the same way for you, just need to make the item container a Panel (rendered as div) so you can hook up a server-side click handler (not sure if Panels can have events tho).

**Comment by Kyewn** [comment]
1. kk
2. no, i did set box shadow to spread until 20px tho, but it should be blurry
3.  Thanks for the insight, will try. For your suggestion using my current method, you're right and that's what I'm trying to do, but backend doesnt let me access DOM elements that weren't `runat="server"`. Even if I specify them as one, I see that my elements are all just of the `Control` type that do not have DOM properties (InnerText), not `HTMLGenericControl`, when I loop through the array and debug the output. Maybe I'm just not getting how to write the code for it, so I'll try again and see if I can do it. If you don't understand, then based on this structure:
```
<div class="listItem">
   <div>
       <span id="lblId"></span>
    </div>
    <div>
    </div>
</div>
```
I need to:
```
// Get array of listItems
foreach (item in array) {
   // Get each list item's span <- I'm stuck here, because I cant get the span using .Controls()
   if (hidden text field id == span's id) {
       // Set css for selected item
       break;
   }
}
```

**Comment by Kyewn** [comment]
Ah, got it working. Used your method by changing listItem type from LiteralControl to Panel, but didnt need to change too much structure. Nice save c:

**Comment by Vaneryn** [comment]
1. I think you should also make the selected item bg-color darker so its more obvious.
2. I think the border is too thicc, 1px or 2px is prolly enough, there are already too many thicc red things around
3. The scrollbar needs to have hover and active bg-color.
Example below:
image

4. Im not sure if the modal shadow is still like this on your side, but it is on mine, and I found out its because you put box-shadow on `.modal-content`, if i put it on `.modal-dialog` instead its fixed.
image

5. You can change the links to `asp:LinkButton` so we can just directly reference them if you want coz this looks unnecessary and a pain to maintain if there are more pages
image

7. In terms of functionality, LGTM to me so far but as of now its just dummy data so its hard to say. We'll need to test more once its integrated with Dictionary and Send Suggestions. Regarding the EF/DB issue, I'm still not getting it, maybe you can get someone else to test it, could somehow be only my PC no problem.

After this should be good to merge if no more issues

**Comment by Kyewn** [comment]
Done

**Comment by Vaneryn** [comment]
LOL POSTBACK?
image

**Comment by Vaneryn** [comment]
1. Link not set to active for homepage URL with no path
image

2. is it just my laptop screen noob or aint this too dark? now the text no longer contrasts with bg, but whatever la dw waste time on design d
image

**Comment by Kyewn** [comment]
i think I used the wrong color, should be same with action menu bg color but used listitem:active color instead

**Comment by Kyewn** [comment]
If no more issues, then I will close this PR. Planning to use back this branch for reports and merge everything later after i open another PR for reports

**Pull request closed without merging**
