### PR TITLE
W05 03 Homepage front-end

### PR DESCRIPTION
**Pull request by Kyewn**
Accidentally merged my fixes directly to Deshi's branch but whatever. Refer to [this pull request](https://github.com/Vaneryn/RojakJelah/pull/3) for more details on my fix. 

This PR is conflicting with `master` and is read-only for now (can't merge directly from here). If we want to accept this change once we confirm this fix is good, we need to resolve the conflicts either:
- on the platform if github feel that is minor conflict, or 
- do it locally and push the changes to the parent branch (`master`) to merge and close this branch. 

I did a mistake in between the process so that's why I accidentally merged it.

### CODE REVIEW

**Review by Vaneryn — CHANGES_REQUESTED** [review]
**Code**
why are the indentations and spacing so inconsistent and spaghetti

**Regarding conflicts**
Merge master into here, then fix the conflicts here before merging into master

**Design**
- input textarea should have resize turned off
- "Translate" button has no hover effect, its active effect stays on until you click elsewhere, its font size is a little too big
- some buttons "hover" effect turn its color darker instead of brighter, like "Learn More"
- this text can be bigger, it being same size/smaller than every other text feels weird since this text is supposed to be the landing header text
image
- the right side should be aligned
image
- back-to-top button hover effect makes the arrow blue (out of theme) ?
- can change the site header text color? its full black makes it feel so out of place compared to the saturated background color theme
image

**Comment by Kyewn** [comment]
- why not let users resize textarea? while it may make the page longer, the user can freely adjust the size if they feel that the input is too small
- Mitr and Rubik fonts are still not used at your side. Still will increase the sizing of the landing header
image

- Site header logo theme "Rojak" orange + "Jelah" yellow good enough?

**Comment by Vaneryn** [comment]
- It's rare to see a user-resizable text-only textarea on most websites/software (unless it's a highly editable textarea like this comment editor that takes more than just text input), most of them are fixed and auto-resize based on user input length, so it's more of a standard thing than how useful it is. But I suppose we should keep it coz I'm too lazy to implement auto-resize
- Yes I noticed after I took the screenshot, text still smol tho
- Not sure how that'd look (might not look good cuz those are secondary colors), maybe #323232 would be enough rather than full black

**Comment by Vaneryn** [comment]
LGTM (don't really wanna bother much about the design anymore c:)

- Still some things can be tweaked (will discuss on the spot tmr easier)
- Add all remaining page files that we may need in the future
- Need to merge master into this branch and resolve conflicts first

We can do all these on the spot tmr I guess, so we don't have anymore stuff need fixing at home

**Review by Vaneryn — DISMISSED** [review]

**Pull request merged**
