### PR TITLE
W07:01 Translator v1

### PR DESCRIPTION
**Pull request by Vaneryn**
**Changes:**
- All frontend on Translator.aspx
- Translation algorithm v1
- Saved translations
- Translation history

### CODE REVIEW

**Comment by Kyewn** [comment]
1. Users can save duplicate records by clicking on the save icon button again
2. The icon state isnt set to 'saved' when a record is already saved.

image

**Review by Kyewn — CHANGES_REQUESTED** [review]
l

**Comment by Vaneryn** [comment]
I didnt really see this as a problem tbh, neither did the lect. If users want to save duplicate or forgot about it, let them go ahead, they can delete it afterwards if they want since its just a minor thing not worth restricting.

If this is the only thing, then we can merge this branch first. I'll compare with other translators and see if they restrict dupes and if they do, i'll implement in algorithm-v2 branch.

**Comment by Kyewn** [comment]
gotcha, all good

**Pull request merged**
